{{- if not .Values.serviceAccountName }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "incerto-collector.fullname" . }}-sa
  namespace: {{ required "A valid .Values.namespace entry required!" .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "incerto-collector.fullname" . }}-cr
  namespace: {{ required "A valid .Values.namespace entry required!" .Values.namespace }}
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "incerto-collector.fullname" . }}-crb
  namespace: {{ required "A valid .Values.namespace entry required!" .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ include "incerto-collector.fullname" . }}-sa
    namespace: clickhouse 
roleRef:
  kind: ClusterRole
  name: {{ include "incerto-collector.fullname" . }}-cr
  apiGroup: rbac.authorization.k8s.io
{{- end }}
