{{- if not .Values.serviceAccountName }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: incerto-reader-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-reader
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-read-binding
subjects:
  - kind: ServiceAccount
    name: incerto-reader-sa
    namespace: clickhouse 
roleRef:
  kind: ClusterRole
  name: cluster-reader
  apiGroup: rbac.authorization.k8s.io
{{- end }}
