image:
  repository: public.ecr.aws/t9w7u8l8/incerto/collector
  tag: "prod"
  pullPolicy: Always

service:
  url: "https://dev.incerto.in"

clickhouse:
  endpoint: "localhost:9000"
  username: "default"
  password: ""

postgres:
  endpoint: "localhost:9000"
  username: "postgres"
  password: "postgres"

nodeSelector: {}
affinity: {}
tolerations: []

resources:
  limits:
    memory: 512Mi
  requests:
    memory: 256Mi