receivers:
  incerto_clickhouse:
    collection_interval: 60s
    flwCommands:
      - endpoint: localhost:9181
        commands:
          - ruok
          - mntr
          - srvr

  hostmetrics:
    root_path: /
    collection_interval: 5s
    scrapers:
      load:
        metrics:
          system.cpu.load_average.15m:
            enabled: true
      memory:
        metrics:
          system.memory.utilization:
            enabled: true
      cpu:
        metrics:
          system.cpu.utilization:
            enabled: true
      filesystem:
        metrics:
          system.filesystem.utilization:
            enabled: true
          system.filesystem.usage:
            enabled: true

exporters:
  
  otlphttp:
    endpoint: ${env:SERVICE_URL}/api/v1/alerts/generated-metrics/${env:HOST_ID}?domain=clickhouse
    metrics_endpoint: ${env:SERVICE_URL}/api/v1/alerts/generated-metrics/${env:HOST_ID}?domain=clickhouse
    encoding: json
    compression: none

  debug:
    verbosity: detailed

service:
  
  pipelines:
    metrics:
      receivers: [hostmetrics, incerto_clickhouse]
      exporters: [debug, otlphttp]
