{{- if and .Values.imagePullSecret.create .Values.aws.accessKeyId .Values.aws.secretAccessKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecret.name }}
  namespace: {{ required "A valid .Values.namespace entry required!" .Values.namespace }}
  labels:
    {{- include "incerto-tool.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf `{"auths":{"434499855633.dkr.ecr.ap-south-1.amazonaws.com":{"username":"AWS","password":"%s","auth":"%s"}}}` (printf "%s:%s" .Values.aws.accessKeyId .Values.aws.secretAccessKey | b64enc) (printf "AWS:%s:%s" .Values.aws.accessKeyId .Values.aws.secretAccessKey | b64enc) | b64enc }}
{{- end }}