apiVersion: v1
kind: Service
metadata:
  name: {{ include "incerto-tool.fullname" . }}
  labels:
    {{- include "incerto-tool.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.ports.http }}
    targetPort: http
    protocol: TCP
    name: http
  - port: {{ .Values.service.ports.https }}
    targetPort: https
    protocol: TCP
    name: https
  selector:
    {{- include "incerto-tool.selectorLabels" . | nindent 4 }}