name: Publish Helm Chart

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      id: checkout-code
      uses: actions/checkout@v4

    - name: Install Helm
      id: install-helm
      uses: azure/setup-helm@v3
      with:
        version: '3.12.0'

    - name: Package and Publish
      run: |
        # Package chart
        helm package collector/helm

        # Setup git
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

        # Try to checkout existing gh-pages or create new one
        git fetch origin gh-pages:gh-pages 2>/dev/null || git checkout --orphan gh-pages
        git checkout gh-pages

        # Clean up everything except .git
        git rm -rf . 2>/dev/null || true

        # Move package to charts directory
        mv *.tgz .

        # Create repository index
        helm repo index charts --url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}

        # Commit and push
        git add .
        git commit -m "Update charts $(date)" || exit 0
        git push origin gh-pages