name: Publish Helm Charts

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      id: checkout-code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install Helm
      id: install-helm
      uses: azure/setup-helm@v3
      with:
        version: '3.12.0'

    - name: Package and Publish
      run: |
        # Setup git
        git config user.name "github-actions"
        git config user.email "github-actions@users.noreply.github.com"

        # Package charts
        helm package collector/helm --destination /tmp
        helm package tool/helm --destination /tmp

        # Check if gh-pages branch exists and switch to it
        if git show-ref --verify --quiet refs/remotes/origin/gh-pages; then
          git checkout gh-pages
        else
          git checkout --orphan gh-pages
          git rm -rf .
        fi

        # Remove any existing charts files (if branch existed)
        rm -f *.tgz index.yaml

        # Copy the new charts
        cp /tmp/*.tgz .

        # Create fresh index with only the latest charts
        helm repo index . --url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}

        # Commit and push
        git add .
        git commit -m "Latest charts release - $(date -u +%Y-%m-%dT%H:%M:%SZ)" || exit 0
        git push origin gh-pages