name: Publish Helm Chart

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      id: checkout-code
      uses: actions/checkout@v4

    - name: Install Helm
      id: install-helm
      uses: azure/setup-helm@v3
      with:
        version: '3.12.0'

    - name: Package and Publish
      run: |
        # Setup git
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        # Package chart
        helm package collector/helm --destination /tmp

        # Switch to gh-pages (create if doesn't exist)
        if git ls-remote --heads origin gh-pages | grep -q gh-pages; then
          git checkout gh-pages
        else
          git checkout --orphan gh-pages
        fi

        # Remove all existing chart files
        rm -f *.tgz index.yaml

        # Copy the new chart
        cp /tmp/*.tgz .

        # Create fresh index with only the latest chart
        helm repo index . --url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}

        # Commit and push
        git add .
        git commit -m "Latest chart release - $(date -u +%Y-%m-%dT%H:%M:%SZ)" || exit 0
        git push origin gh-pages