name: Publish Helm Chart

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      id: checkout-code
      uses: actions/checkout@v4

    - name: Install Helm
      id: install-helm
      uses: azure/setup-helm@v3
      with:
        version: '3.12.0'

    - name: Package and Publish
      run: |
        # Package chart
        helm package collector/helm

        # Setup git
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

        # Switch to gh-pages branch (create if doesn't exist)
        git checkout gh-pages 2>/dev/null || git checkout -b gh-pages

        # Move package to charts directory
        mkdir -p charts
        mv *.tgz charts/

        # Create repository index
        helm repo index charts --url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}

        # Copy index to root
        cp charts/index.yaml .

        # Commit and push
        git add .
        git commit -m "Update charts" || exit 0
        git push origin gh-pages